❯ make test
python3 -m unittest discover tests
F.F...EEEEEEE....../home/romankozak/studio/public/code_agent/modules/logger.py:19: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/romankozak/studio/public/code_agent/communication.log' mode='w' encoding='utf-8'>
  comm_logger.handlers.clear()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/romankozak/studio/public/code_agent/modules/logger.py:21: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/romankozak/studio/public/code_agent/debug.log' mode='w' encoding='utf-8'>
  debug_logger.handlers.clear()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib64/python3.14/unittest/mock.py:2601: RuntimeWarning: coroutine 'AsyncMockMixin._execute_mock_call' was never awaited
  return tuple.__new__(cls, (name, args, kwargs))
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
^[Executing <Task pending name='Task-73' coro=<TestHistoryLogic.test_failed_execution_history() running at /home/romankozak/studio/public/code_agent/tests/test_history_logic.py:60> wait_for=<Task pending name='Task-2793' coro=<AsyncMockMixin._execute_mock_call() running at /usr/lib64/python3.14/unittest/mock.py:2314> cb=[Task.task_wakeup()] created at /usr/lib64/python3.14/asyncio/tasks.py:395> cb=[_run_until_complete_cb() at /usr/lib64/python3.14/asyncio/base_events.py:181] created at /usr/lib64/python3.14/asyncio/runners.py:109> took 0.115 seconds
Executing <Task pending name='Task-73' coro=<TestHistoryLogic.test_failed_execution_history() running at /home/romankozak/studio/public/code_agent/tests/test_history_logic.py:60> wait_for=<Task pending name='Task-5737' coro=<AsyncMockMixin._execute_mock_call() running at /usr/lib64/python3.14/unittest/mock.py:2314> cb=[Task.task_wakeup()] created at /usr/lib64/python3.14/asyncio/tasks.py:395> cb=[_run_until_complete_cb() at /usr/lib64/python3.14/asyncio/base_events.py:181] created at /usr/lib64/python3.14/asyncio/runners.py:109> took 0.247 seconds
Executing <Task pending name='Task-73' coro=<TestHistoryLogic.test_failed_execution_history() running at /home/romankozak/studio/public/code_agent/tests/test_history_logic.py:60> wait_for=<Task pending name='Task-9656' coro=<AsyncMockMixin._execute_mock_call() running at /usr/lib64/python3.14/unittest/mock.py:2314> cb=[Task.task_wakeup()] created at /usr/lib64/python3.14/asyncio/tasks.py:395> cb=[_run_until_complete_cb() at /usr/lib64/python3.14/asyncio/base_events.py:181] created at /usr/lib64/python3.14/asyncio/runners.py:109> took 0.124 seconds
Executing <Task pending name='Task-73' coro=<TestHistoryLogic.test_failed_execution_history() running at /home/romankozak/studio/public/code_agent/tests/test_history_logic.py:60> wait_for=<Task pending name='Task-11601' coro=<AsyncMockMixin._execute_mock_call() running at /usr/lib64/python3.14/unittest/mock.py:2314> cb=[Task.task_wakeup()] created at /usr/lib64/python3.14/asyncio/tasks.py:395> cb=[_run_until_complete_cb() at /usr/lib64/python3.14/asyncio/base_events.py:181] created at /usr/lib64/python3.14/asyncio/runners.py:109> took 0.508 seconds